### ISSUE TITLE
登录

### ISSUE THREAD

**Issue by Lily9966** [Maicius/QQZoneMood#27]
登录时经常出现qq号和识别码不匹配和qq号和cookie不匹配的问题，可我输入的时候是没有错的

**Comment by Maicius** [comment]
请详细描述一下你使用的代码版本
qq号与识别码不匹配的问题我在服务器版本上复现过，这主要是因为爬虫的一次http请求过长导致的，应该早就修复了，现在出现网络问题都会统一提示“由于网络原因.....”。
qq号与cookie不匹配的问题也可能是网络的问题，无法使用该cookie完成登陆就会出现那个原因。
