### ISSUE TITLE
本地部署问题

### ISSUE THREAD

**Issue by MiChongGET** [Maicius/QQZoneMood#36]
服务器控制台报错，好像爬取数据失败了，显示“服务器比较忙，请稍后再试”

**Comment by Maicius** [comment]
是腾讯的服务器有点不堪压力，可以把线程数量调小一点或者过一段时间再试。一般在爬取的时候会出现少量这种错误，但是有异常处理，应该不会导致程序运行出错，除非一条数据都没获取到。

**Comment by MiChongGET** [comment]
我这是本地跑的docker，出现了这种错误，会不会是QQ有反爬虫机制，我看了redis，数据大部分获取到了，但是获取好友的时候就卡住了，总是剩十几个获取不到

**Comment by Maicius** [comment]
抱歉，这是我程序的bug，我刚刚修复了，当有一个好友数据出错时那个线程会陷入死循环。另外，如果需要修改线程数量的话，只需要修改BaseSpider中的self.thread_num就行。

**Comment by MiChongGET** [comment]
好的谢谢啦，最新代码提交了吗，我还想跑一跑代码

**Comment by Maicius** [comment]
已经提交了，但需要注意的是，目前如果获取好友数据时出错了，那条数据就不会被记录在结果中，这就是说，如果你有1500个好友，但只成功获取了1200个好友数据，进度条就会卡在1200/1500，等获取动态的数据结束之后会一起结束。我后面会再修改一下策略
