### ISSUE TITLE
如果能分析指定日期之后的说说数据就好了，比如我想分析2017年至今的

### ISSUE THREAD

**Issue by Vince-9** [Maicius/QQZoneMood#44]

**Comment by Maicius** [comment]
该功能已经实现了，但是没有整合到线上。代码里已经提供了完整的接口，除了设置停止日期外，还可以设置停止数量，比如只爬取最新的100条说说等，具体的功能可以到这个文件查看：
https://github.com/Maicius/QQZoneMood/blob/master/src/spider/main.py
，只需要运行该接口：capture_main_data_and_analysis就行
