### ISSUE TITLE
如何爬取好友空间

### ISSUE THREAD

**Issue by lxy444** [Maicius/QQZoneMood#45]
从知乎上看过来的，感谢大神分享，想问一下如果要爬某个好友 A 的空间(有 QQ 号和访问权限)，需要修改 src/spider/main.py 中的哪些参数呢？

**Comment by Maicius** [comment]
调用函数generate_friend_info()，

```
def generate_friend_info():
    """
    获取好友的空间数据并进行数据分析
    :return:
    """
    qa = QQZoneAnalysis(use_redis=False, debug=False, analysis_friend=False, mood_num=20)
    # 建议在resource/config/friend_info.json中配置需要爬取的好友QQ号
    # 也可以直接在这里传入qq号，此处传入的QQ号优先级比配置文件大，但是配置文件可以批量传入QQ号
    qa.get_friend_mood(friend_qq='')
    do_analysis_for_all(qa)
```
如果只需要爬取一个好友的账号，可以直接在 qa.get_friend_mood(friend_qq='')传入qq号，如果要爬取多个，在resource/config/friend_info.json根据模板修改配置文件即可

**Comment by lxy444** [comment]
感谢说明，我修改了之后，运行`src/spider/main.py` 可以爬取到该好友全部的说说数据了，不过可视化方面只生成了一个点赞的词云图，没有说说关键字的词云图，此外也想生成网页上的历史曲线图，是否应该运行`src/web/server.py`文件呢？

PS1: 我运行了`src/web/server.py`文件之后，报如下错误：

> Failed to connect redis: Error 8 connecting to redis:6379. nodename nor servname provided, or not known.

请问是还需要其他操作吗？

PS2: 补充一点，就是在 mac 上运行代码的时候，发现会报错

> RuntimeError: Calling Tcl from different appartment

然后发现是`openpyxl`的版本过高, 降级成 2.6.3 就可以了，供后面的人参考。

**Comment by Maicius** [comment]
运行server需要安装redis，这个报错因为无法连接redis。

生成曲线的功能没有提供接口，获取好友的数据只能得到词云图和excel文件。要绘制历史曲线得依靠网页，这部分改动起来比较大，我后面有空了再考虑。

**Comment by lxy444** [comment]
已经成功运行，谢谢！
