### ISSUE TITLE
最新版本登录成功后提示未登录

### ISSUE THREAD

**Issue by kapmix** [Maicius/QQZoneMood#48]
最新版本登录成功后提示未登录

**Comment by Maicius** [comment]
我在本地和服务器上测试都没有出现问题，请详细描述一下出错或提示的情况，最好附上截图

**Comment by kapmix** [comment]
前两天运行一直报错: 输入密码, 手动验证图形以后, 报错说未登陆.

现在一切正常了. 请忽略我的提问.
