### ISSUE TITLE
使用python版本爬取他人空间意外退出

### ISSUE THREAD

**Issue by Tim-Siu** [Maicius/QQZoneMood#50]
success to download qr code
2020-04-28 17:39:56.562 Python[1922:60833] WARNING: NSWindow drag regions should only be invalidated on the Main Thread! This will throw an exception in the future. Called from (
	0   AppKit                              0x00007fff30227289 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 371
	1   AppKit                              0x00007fff3020ecb2 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1416
	2   AppKit                              0x00007fff3020e723 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
	3   _macosx.cpython-38-darwin.so        0x000000011833b7c0 -[Window initWithContentRect:styleMask:backing:defer:withManager:] + 80
	4   _macosx.cpython-38-darwin.so        0x000000011833eccf FigureManager_init + 319
	5   Python                              0x000000010d3a9dfc wrap_init + 12
	6   Python                              0x000000010d35b599 wrapperdescr_call + 121
	7   Python                              0x000000010d352785 _PyObject_MakeTpCall + 373
	8   Python                              0x000000010d420ed5 call_function + 533
	9   Python                              0x000000010d41dc8d _PyEval_EvalFrameDefault + 25677
	10  Python                              0x000000010d3530d0 function_code_fastcall + 128
	11  Python                              0x000000010d3525d7 _PyObject_FastCallDict + 247
	12  Python                              0x000000010d353bdf _PyObject_Call_Prepend + 143
	13  Python                              0x000000010d3a9d41 slot_tp_init + 145
	14  Python                              0x000000010d3a5219 type_call + 297
	15  Python                              0x000000010d352785 _PyObject_MakeTpCall + 373
	16  Python                              0x000000010d420ed5 call_function + 533
	17  Python                              0x000000010d41dc8d _PyEval_EvalFrameDefault + 25677
	18  Python                              0x000000010d3530d0 function_code_fastcall + 128
	19  Python                              0x000000010d35579a method_vectorcall + 170
	20  Python                              0x000000010d420e7c call_function + 444
	21  Python                              0x000000010d41dc8d _PyEval_EvalFrameDefault + 25677
	22  Python                              0x000000010d421cc4 _PyEval_EvalCodeWithName + 2804
	23  Python                              0x000000010d35326e _PyFunction_Vectorcall + 270
	24  Python                              0x000000010d35587c method_vectorcall + 396
	25  Python                              0x000000010d352aad PyVectorcall_Call + 109
	26  Python                              0x000000010d41e198 _PyEval_EvalFrameDefault + 26968
	27  Python                              0x000000010d421cc4 _PyEval_EvalCodeWithName + 2804
	28  Python                              0x000000010d35326e _PyFunction_Vectorcall + 270
	29  Python                              0x000000010d420e7c call_function + 444
	30  Python                              0x000000010d41dd1a _PyEval_EvalFrameDefault + 25818
	31  Python                              0x000000010d3530d0 function_code_fastcall + 128
	32  Python                              0x000000010d420e7c call_function + 444
	33  Python                              0x000000010d41dd1a _PyEval_EvalFrameDefault + 25818
	34  Python                              0x000000010d421cc4 _PyEval_EvalCodeWithName + 2804
	35  Python                              0x000000010d35326e _PyFunction_Vectorcall + 270
	36  Python                              0x000000010d420e7c call_function + 444
	37  Python                              0x000000010d41dd1a _PyEval_EvalFrameDefault + 25818
	38  Python                              0x000000010d421cc4 _PyEval_EvalCodeWithName + 2804
	39  Python                              0x000000010d35326e _PyFunction_Vectorcall + 270
	40  Python                              0x000000010d420e7c call_function + 444
	41  Python                              0x000000010d41dc8d _PyEval_EvalFrameDefault + 25677
	42  Python                              0x000000010d3530d0 function_code_fastcall + 128
	43  Python                              0x000000010d35587c method_vectorcall + 396
	44  Python                              0x000000010d352aad PyVectorcall_Call + 109
	45  Python                              0x000000010d41e198 _PyEval_EvalFrameDefault + 26968
	46  Python                              0x000000010d3530d0 function_code_fastcall + 128
	47  Python                              0x000000010d420e7c call_function + 444
	48  Python                              0x000000010d41dc69 _PyEval_EvalFrameDefault + 25641
	49  Python                              0x000000010d3530d0 function_code_fastcall + 128
	50  Python                              0x000000010d420e7c call_function + 444
	51  Python                              0x000000010d41dc69 _PyEval_EvalFrameDefault + 25641
	52  Python                              0x000000010d3530d0 function_code_fastcall + 128
	53  Python                              0x000000010d3557db method_vectorcall + 235
	54  Python                              0x000000010d352aad PyVectorcall_Call + 109
	55  Python                              0x000000010d4c07da t_bootstrap + 74
	56  Python                              0x000000010d473b19 pythread_wrapper + 25
	57  libsystem_pthread.dylib             0x00007fff6d0c8109 _pthread_start + 148
	58  libsystem_pthread.dylib             0x00007fff6d0c3b8b thread_start + 15
)
2020-04-28 17:39:56.718 Python[1922:60833] WARNING: nextEventMatchingMask should only be called from the Main Thread! This will throw an exception in the future.
2020-04-28 17:39:56.718 Python[1922:60833] *** Assertion failure in +[NSUndoManager _endTopLevelGroupings], /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/Foundation/Foundation-1675.129/Foundation/Misc.subproj/NSUndoManager.m:363
2020-04-28 17:39:56.720 Python[1922:60833] *** Assertion failure in +[NSUndoManager _endTopLevelGroupings], /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/Foundation/Foundation-1675.129/Foundation/Misc.subproj/NSUndoManager.m:363
2020-04-28 17:39:56.723 Python[1922:60833] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '+[NSUndoManager(NSInternal) _endTopLevelGroupings] is only safe to invoke on the main thread.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff32ff7d07 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff6bd1c5bf objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff33020ec8 +[NSException raise:format:arguments:] + 88
	3   Foundation                          0x00007fff3570bf3d -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
	4   Foundation                          0x00007fff356486ce +[NSUndoManager(NSPrivate) _endTopLevelGroupings] + 440
	5   AppKit                              0x00007fff301e92bc -[NSApplication run] + 864
	6   _macosx.cpython-38-darwin.so        0x0000000118340132 show + 210
	7   Python                              0x000000010d38f2b6 cfunction_vectorcall_NOARGS + 214
	8   Python                              0x000000010d420e7c call_function + 444
	9   Python                              0x000000010d41dc8d _PyEval_EvalFrameDefault + 25677
	10  Python                              0x000000010d3530d0 function_code_fastcall + 128
	11  Python                              0x000000010d420e7c call_function + 444
	12  Python                              0x000000010d41dc8d _PyEval_EvalFrameDefault + 25677
	13  Python                              0x000000010d421cc4 _PyEval_EvalCodeWithName + 2804
	14  Python                              0x000000010d35326e _PyFunction_Vectorcall + 270
	15  Python                              0x000000010d352aad PyVectorcall_Call + 109
	16  Python                              0x000000010d41e198 _PyEval_EvalFrameDefault + 26968
	17  Python                              0x000000010d421cc4 _PyEval_EvalCodeWithName + 2804
	18  Python                              0x000000010d35326e _PyFunction_Vectorcall + 270
	19  Python                              0x000000010d3557db method_vectorcall + 235
	20  Python                              0x000000010d352aad PyVectorcall_Call + 109
	21  Python                              0x000000010d41e198 _PyEval_EvalFrameDefault + 26968
	22  Python                              0x000000010d421cc4 _PyEval_EvalCodeWithName + 2804
	23  Python                              0x000000010d35326e _PyFunction_Vectorcall + 270
	24  Python                              0x000000010d420e7c call_function + 444
	25  Python                              0x000000010d41dc8d _PyEval_EvalFrameDefault + 25677
	26  Python                              0x000000010d3530d0 function_code_fastcall + 128
	27  Python                              0x000000010d35587c method_vectorcall + 396
	28  Python                              0x000000010d352aad PyVectorcall_Call + 109
	29  Python                              0x000000010d41e198 _PyEval_EvalFrameDefault + 26968
	30  Python                              0x000000010d3530d0 function_code_fastcall + 128
	31  Python                              0x000000010d420e7c call_function + 444
	32  Python                              0x000000010d41dc69 _PyEval_EvalFrameDefault + 25641
	33  Python                              0x000000010d3530d0 function_code_fastcall + 128
	34  Python                              0x000000010d420e7c call_function + 444
	35  Python                              0x000000010d41dc69 _PyEval_EvalFrameDefault + 25641
	36  Python                              0x000000010d3530d0 function_code_fastcall + 128
	37  Python                              0x000000010d3557db method_vectorcall + 235
	38  Python                              0x000000010d352aad PyVectorcall_Call + 109
	39  Python                              0x000000010d4c07da t_bootstrap + 74
	40  Python                              0x000000010d473b19 pythread_wrapper + 25
	41  libsystem_pthread.dylib             0x00007fff6d0c8109 _pthread_start + 148
	42  libsystem_pthread.dylib             0x00007fff6d0c3b8b thread_start + 15
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6
运行main.py ,生成二维码后意外退出，macOS 15.4 ，python 3.8.2环境
本人小白一位🤦‍♂️

**Comment by Maicius** [comment]
这应该是macOS 新增的特性，只允许在主线程中弹出NSWindow，参考：https://trac.macports.org/ticket/58794
代码src/spider/QQZoneSpider第119行附近使用了subprocess 来调用NSWindow弹出二维码，因此出现该错误。已修改改为os.system直接打开，若打开失败请根据提示手动寻找二维码图片进行扫描
