### ISSUE TITLE
多线程会遗漏数据

### ISSUE THREAD

**Issue by lxy444** [Maicius/QQZoneMood#55]
使用默认的线程数(10)跑程序的时候，某些线程抓取失败，导致爬取的数据不全(QQ 空间说说)，请问楼主这个怎么解决呢

**Comment by Maicius** [comment]
目前程序的策略是：遇到错误循环五次，第一次sleep 1秒，第二次sleep 2秒，以此类推。如果5次之后还是失败，就放弃。因为有的数据确实获取不了了，qq空间的服务器不稳定，即使在电脑端正常访问，也经常有加载不出来的情况。甚至有数据已经确定丢失了，多年前说说的点赞好友信息

**Comment by lxy444** [comment]
> 目前程序的策略是：遇到错误循环五次，第一次sleep 1秒，第二次sleep 2秒，以此类推。如果5次之后还是失败，就放弃。因为有的数据确实获取不了了，qq空间的服务器不稳定，即使在电脑端正常访问，也经常有加载不出来的情况。甚至有数据已经确定丢失了，多年前说说的点赞好友信息

好的，感谢楼主！(用了单线程爬取到全部数据了，虽然比较慢)
