### ISSUE TITLE
json以及csv文件

### ISSUE THREAD

**Issue by BryanHuang66** [Maicius/QQZoneMood#6]
新手一枚，只是希望爬一点数据。为什么代码不会自动创建maicius_friend_detail_list.csv文件，我在文件夹中创建了一个后，运行又出现File "pandas\_libs\parsers.pyx", line 545, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file。

**Comment by Maicius** [comment]
请详细描述一下您是怎么运行的，以及运行的哪个类。
maicius_friend_detail_list.csv这个文件是在QQZoneFriendSpider.py文件中创建的，它保存的是经过清洗过后的好友数据。
